name: Build APK with Apktool

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Apktool
        run: java -jar apktool.jar --version

      - name: Verify Apktool
        run: java -jar apktool.jar d -s app.apk

      - name: Verify Apktool
        run: cat net.xml > cat app/res/xml/network_security_config.xml

      - name: Build APK
        run: |
          java -jar apktool.jar b app

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: rebuilt-apk
          path: app/dist/*.apk
